ASM_ASPNETCORE/Areas/Admin/Controllers/HomeAdminController.cs
using ASM_ASPNETCORE.DAL;
using ASM_ASPNETCORE.DTO;
using ASM_ASPNETCORE.Models;
using ASM_ASPNETCORE.Utils;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;

namespace ASM_ASPNETCORE.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Route("admin")]
	
	public class HomeAdminController : Controller
	{
		private AdminUserDAL _adminUserDAL;
		private readonly IConfiguration _configuration;
		public HomeAdminController(IConfiguration configuration)
		{
			_configuration = configuration;
			_adminUserDAL = new AdminUserDAL(_configuration);
		}

		[HttpGet("")]
		[HttpGet("login")]
		public IActionResult Index()
		{
			var login = Request.Cookies.Get<LoginDTO>("UserCredential");
			return DoLogin(login);
		}
		[HttpPost("")]
		[HttpPost("login")]
		public IActionResult Index(LoginDTO login)
		{
			return DoLogin(login);
		}

		private IActionResult DoLogin(LoginDTO? login)
		{
			if(login != null)
			{
				var result = _adminUserDAL.Authenticate(login.Email_Admin, login.Password);
				if(result != null)
				{
					// Check Remember for next time
					if(login.RememberMe)
					{
						// Add a cookie
						Response.Cookies.Append<LoginDTO>("UserCredential", login, new CookieOptions
						{
							Expires = DateTimeOffset.UtcNow.AddDays(7),
							HttpOnly = true,
							IsEssential = true
						});
					}
					HttpContext.Session.Set<AdminUser>("userInfo", result);
					return RedirectToAction("dashboard");
				}
				else
				{
					ViewData["Message"] = "Wrong username or password!";
				}
			}
			return View();
		}
		[HttpGet("dashboard")]
		public IActionResult Dashboard()
		{
			return View();
		}

	}
}

ASM_ASPNETCORE/Areas/Admin/Views/HomeAdmin/Dashboard.cshtml
@{
	Layout = "/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<h1 class="text-center text-primary mt-5">Welcome to Fruit Shop Admin Site!</h1>

ASM_ASPNETCORE/Areas/Admin/Views/HomeAdmin/Index.cshtml
@model ASM_ASPNETCORE.DTO.LoginDTO
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Electronics Admin | Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="title" content="FruitShop Admin | Login">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@@fontsource/source-sans-3@5.0.12/index.css" />
    <link rel="stylesheet" href="~/Admin/plugins/overlayscrollbars/styles/overlayscrollbars.min.css" />
    <link rel="stylesheet" href="~/Admin/plugins/bootstrap-icons/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="~/Admin/plugins/font-awesome/css/all.css" />
    <link rel="stylesheet" href="~/Admin/css/adminlte.css" />
    <link rel="stylesheet" href="~/Admin/css/custom.css" />
</head>
<body class="login-page bg-body-secondary">
    <div class="login-box">
        <div class="card card-outline card-primary">
            <div class="card-header">
                <h1 class="mb-0">Admin Login</h1>
            </div>
            <div class="card-body login-card-body rounded">
                <p class="login-box-msg text-danger">@ViewData["Message"]</p>
                <form method="post" asp-area="Admin" asp-controller="HomeAdmin" asp-action="Index">
                    <div class="input-group mb-2">
                        <div class="form-floating">
                            <input id="loginUsername" asp-for="@Model.Email_Admin" type="text" class="form-control" value="" placeholder="">
                            <label for="loginUsername">Username</label>
                        </div>
                        <div class="input-group-text"> <i class="fa-light fa-user"></i> </div>
                    </div>
                    <div class="input-group mb-3">
                        <div class="form-floating">
                            <input id="loginPassword" asp-for="@Model.Password" type="password" class="form-control" placeholder="">
                            <label for="loginPassword">Password</label>
                        </div>
                        <div class="input-group-text"> <i class="fa-light fa-lock"></i> </div>
                    </div> <!--begin::Row-->
                    <div class="row">
                        <div class="col-8 d-inline-flex align-items-center">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" asp-for="@Model.RememberMe">
                                <label class="form-check-label" asp-for="@Model.RememberMe">
                                    Remember Me
                                </label>
                            </div>
                        </div> <!-- /.col -->
                        <div class="col-4">
                            <div class="d-grid gap-2"> <button type="submit" class="btn btn-primary">Sign In</button> </div>
                        </div> <!-- /.col -->
                    </div> <!--end::Row-->
                </form>
            </div> <!-- /.login-card-body -->
        </div>
    </div> <!-- /.login-box -->
   <script src="~/Admin/plugins/overlayscrollbars/browser/overlayscrollbars.browser.es6.min.js"></script>
    <script src="~/Admin/js/bootstrap.bundle.min.js"></script>
    <script src="~/Admin/js/adminlte.js"></script>
    <script src="~/Admin/plugins/jquery/jquery-3.7.1.min.js"></script>
</body>
</html>