ASM_ASPNETCORE/Models/Product.cs
using Microsoft.CodeAnalysis.Options;
using System.Drawing;

namespace ASM_ASPNETCORE.Models
{
    public class Product
    {
        public int ID_SANPHAM { get; set; }
        public string MA_SANPHAM { get; set; } = string.Empty;
        public string TEN_SANPHAM { get; set; } = string.Empty;
        public string HINH_SANPHAM { get; set; } = string.Empty;
        public int SOLUONG_SANPHAM { get; set; }
        public Decimal GIA_SANPHAM { get; set; }
        public string TINHTRANG_SANPHAM { get; set; } = string.Empty;
        public string MOTA_SANPHAM { get; set; } = string.Empty;
        public string MA_ADMIN { get; set; } = string.Empty;

    }
}

ASM_ASPNETCORE/Areas/Admin/Controllers/ProductController.cs
using ASM_ASPNETCORE.DAL;
using ASM_ASPNETCORE.Models;
using ASM_ASPNETCORE.Utils;
using Microsoft.AspNetCore.Mvc;

namespace ASM_ASPNETCORE.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly ProductDAL _productDAL;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductController(IConfiguration configuration, IWebHostEnvironment webHostEnvironment)
        {
            _productDAL = new ProductDAL(configuration);
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            var products = _productDAL.GetList();
            return View(products);
        }
        #region CreateProduct
        #region CreateProduct
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Product product, IFormFile HINH_SANPHAM)
        {
            if (ModelState.IsValid)
            {
                if (HINH_SANPHAM != null && HINH_SANPHAM.Length > 0)
                {
                    // Đường dẫn thư mục để lưu file hình ảnh
                    var uploadsDirectory = Path.Combine(_webHostEnvironment.WebRootPath, "LayoutElectronic");

                    // Tạo thư mục nếu nó chưa tồn tại
                    if (!Directory.Exists(uploadsDirectory))
                    {
                        Directory.CreateDirectory(uploadsDirectory);
                    }

                    // Lấy tên file và tạo đường dẫn
                    var fileName = Path.GetFileName(HINH_SANPHAM.FileName);
                    var filePath = Path.Combine(uploadsDirectory, fileName);

                    // Lưu file hình ảnh vào thư mục
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await HINH_SANPHAM.CopyToAsync(stream);
                    }

                    // Lưu đường dẫn của ảnh vào product
                    product.HINH_SANPHAM = "/LayoutElectronic/" + fileName;
                }

                // Thêm sản phẩm vào database
                _productDAL.ThemSanPham(product);

                return RedirectToAction(nameof(Index));
            }

            return View(product);
        }
        #endregion

        #endregion
        #region UpdateProduct
        [HttpGet]
        public IActionResult Edit(string maSP)
        {
            var product = _productDAL.GetProductByMaSP(maSP);
            return View(product);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Product product, IFormFile HINH_SANPHAM)
        {
            if (ModelState.IsValid)
            {
                if (HINH_SANPHAM != null)
                {
                    var uploadsDirectory = Path.Combine(_webHostEnvironment.WebRootPath, "LayoutElectronic");

                    // Tạo thư mục nếu nó chưa tồn tại
                    if (!Directory.Exists(uploadsDirectory))
                    {
                        Directory.CreateDirectory(uploadsDirectory);
                    }

                    var fileName = Path.GetFileName(HINH_SANPHAM.FileName);
                    var filePath = Path.Combine(uploadsDirectory, fileName);

                    // Lưu file vào thư mục
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await HINH_SANPHAM.CopyToAsync(stream);
                    }

                    product.HINH_SANPHAM = "/LayoutElectronic/" + fileName; // Lưu đường dẫn của ảnh vào product
                }

                // Cập nhật sản phẩm vào database
                _productDAL.CapNhatSanPham(product);

                return RedirectToAction(nameof(Index));
            }

            return View(product);
        }
        #endregion
        #region DeleteProduct
        [HttpGet]
        public IActionResult Delete(string maSP)
        {
            var product = _productDAL.GetProductByMaSP(maSP);
            if(product == null)
            {
                return NotFound();
            }
            return View(product);
        }
        [HttpPost]
        public IActionResult DeleteConfirm(string maSP)
        {
            _productDAL.XoaSanPhamTheoMaSP(maSP);
            return RedirectToAction(nameof(Index));
        }
        #endregion
        










    }
}

ASM_ASPNETCORE/Controllers/ProductController.cs
using ASM_ASPNETCORE.DAL;
using Microsoft.AspNetCore.Mvc;

namespace ASM_ASPNETCORE.Controllers
{
    public class ProductController : Controller
    {
        private readonly ProductDAL _productDAL;
        public ProductController(IConfiguration configuration)
        {
            _productDAL = new ProductDAL(configuration);
        }
        public IActionResult Index()
        {
            var products = _productDAL.GetProducts();
            if(products == null || !products.Any())
            {
                Console.WriteLine("No products found");
            }
            var topProducts = products.Take(8).ToList();
            return View(topProducts);
        }

        public IActionResult Details(string maSP)
        {
            var product = _productDAL.GetProductByMaSP(maSP);
            if(product == null)
            {
                return NotFound();
            }
            return View(product);
        }
    }
}

ASM_ASPNETCORE/Controllers/ShoppingCartController.cs
using ASM_ASPNETCORE.DAL;
using Microsoft.AspNetCore.Mvc;

namespace ASM_ASPNETCORE.Controllers
{
	public class ShoppingCartController : Controller
	{
		private readonly CartDAL _cartDAL;
		public ShoppingCartController(IConfiguration configuration)
		{
			_cartDAL = new CartDAL(configuration);
		}
		public IActionResult Index(string maNguoiDung)
		{
			var cartItem = _cartDAL.GetListCartByMaND(maNguoiDung);
			return View(cartItem);
		}
        [HttpPost]
        public IActionResult AddToCart(string maSanPham, int soLuong = 1) // Số lượng mặc định là 1
        {
            string maNguoiDung = "ND_0001"; // Lấy email người dùng từ session hoặc model

            // Thêm sản phẩm vào giỏ hàng
            _cartDAL.AddToCart(maSanPham, soLuong, maNguoiDung);

            // Chuyển hướng về trang giỏ hàng hoặc trang sản phẩm
            return RedirectToAction("Index", "Cart"); // Giả sử bạn có trang Index để hiển thị giỏ hàng
        }

    }
}

ASM_ASPNETCORE/Views/Product/Details.cshtml
@model ASM_ASPNETCORE.Models.Product
@{
	ViewData["Title"] = "Details";
	Layout = "~/Views/Shared/_Layout.cshtml";
}





<section class="product-details spad">
	<div class="container">
		<div class="row">
			<div class="col-lg-6 col-md-6">
				<div class="product__details__pic">
					<div class="product__details__pic__item">
						<img class="product__details__pic__item--large"
							 src="@Model.HINH_SANPHAM" alt="@Model.TEN_SANPHAM">
					</div>
					<div class="product__details__pic__slider owl-carousel">
						<img data-imgbigurl="~/LayoutElectronic/img/product/featuredt-7.jpg"
							 src="~/LayoutElectronic/img/product/featuredt-4.jpg" alt="">
						<img data-imgbigurl="~/LayoutElectronic/img/product/featuredt-6.jpg"
							 src="~/LayoutElectronic/img/product/featuredt-7.jpg" alt="">
						<img data-imgbigurl="~/LayoutElectronic/img/product/featuredt-7.jpg"
							 src="~/LayoutElectronic/img/product/featuredt-7.jpg" alt="">
						<img data-imgbigurl="~/LayoutElectronic/img/product/featuredt-7.jpg"
							 src="~/LayoutElectronic/img/product/featuredt-7.jpg" alt="">
					</div>
				</div>
			</div>
			<div class="col-lg-6 col-md-6">
				<div class="product__details__text">
					<h3>Electronics </h3>
					<div class="product__details__rating">
						<i class="fa fa-star"></i>
						<i class="fa fa-star"></i>
						<i class="fa fa-star"></i>
						<i class="fa fa-star"></i>
						<i class="fa fa-star-half-o"></i>
						<span>(18 reviews)</span>
					</div>
					<div class="product__details__price">@Model.GIA_SANPHAM</div>
					<p>
						@Model.MOTA_SANPHAM
					</p>
					<div class="product__details__quantity">
						<div class="quantity">
							<div class="pro-qty">
								<input type="text" value="1">
							</div>
						</div>
					</div>
					<a href="#" class="primary-btn">ADD TO CARD</a>
					<a href="#" class="heart-icon"><span class="icon_heart_alt"></span></a>
					<ul>
						<li><b>Availability</b> <span>In Stock</span></li>
						<li><b>Shipping</b> <span>01 day shipping. <samp>Free pickup today</samp></span></li>
						<li><b>Weight</b> <span>0.5 kg</span></li>
						<li>
							<b>Share on</b>
							<div class="share">
								<a href="#"><i class="fa fa-facebook"></i></a>
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="#"><i class="fa fa-instagram"></i></a>
								<a href="#"><i class="fa fa-pinterest"></i></a>
							</div>
						</li>
					</ul>
				</div>
			</div>
			<div class="col-lg-12">
				<div class="product__details__tab">
					<ul class="nav nav-tabs" role="tablist">
						<li class="nav-item">
							<a class="nav-link active" data-toggle="tab" href="#tabs-1" role="tab"
							   aria-selected="true">Description</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" data-toggle="tab" href="#tabs-2" role="tab"
							   aria-selected="false">Information</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" data-toggle="tab" href="#tabs-3" role="tab"
							   aria-selected="false">Reviews <span>(1)</span></a>
						</li>
					</ul>
					<div class="tab-content">
						<div class="tab-pane active" id="tabs-1" role="tabpanel">
							<div class="product__details__tab__desc">
								<h6>Products Infomation</h6>
								<p>
									Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui.
									Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus
									suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam
									vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada.
									Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat,
									accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a
									pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula
									elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus
									et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam
									vel, ullamcorper sit amet ligula. Proin eget tortor risus.
								</p>
								<p>
									Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem
									ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet
									elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum
									porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus
									nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a.
									Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed
									porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum
									sed sit amet dui. Proin eget tortor risus.
								</p>
							</div>
						</div>
						<div class="tab-pane" id="tabs-2" role="tabpanel">
							<div class="product__details__tab__desc">
								<h6>Products Infomation</h6>
								<p>
									Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui.
									Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus.
									Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam
									sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo
									eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat.
									Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent
									sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac
									diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante
									ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
									Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula.
									Proin eget tortor risus.
								</p>
								<p>
									Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem
									ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet
									elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum
									porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus
									nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a.
								</p>
							</div>
						</div>
						<div class="tab-pane" id="tabs-3" role="tabpanel">
							<div class="product__details__tab__desc">
								<h6>Products Infomation</h6>
								<p>
									Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui.
									Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus.
									Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam
									sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo
									eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat.
									Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent
									sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac
									diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante
									ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
									Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula.
									Proin eget tortor risus.
								</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

ASM_ASPNETCORE/Views/Product/Index.cshtml
@model List<ASM_ASPNETCORE.Models.Product>

<!-- Categories Section Begin -->
<section class="categories" style="margin-bottom: 10px">
	<div class="container">
		<div class="row">
			<div class="categories__slider owl-carousel">
				<div class="col-lg-3">
					<div class="categories__item set-bg" data-setbg="../LayoutElectronic/img/categories/catdt-1.jpg">
						<h5><a href="#">Laptop</a></h5>
					</div>
				</div>
				<div class="col-lg-3">
					<div class="categories__item set-bg" data-setbg="../LayoutElectronic/img/categories/catdt-2.jpg">
						<h5><a href="#">Đồng hồ</a></h5>
					</div>
				</div>
				<div class="col-lg-3">
					<div class="categories__item set-bg" data-setbg="../LayoutElectronic/img/categories/catdt-3.jpg">
						<h5><a href="#">Iphone 16 Promax</a></h5>
					</div>
				</div>
				<div class="col-lg-3">
					<div class="categories__item set-bg" data-setbg="../LayoutElectronic/img/categories/catdt-4.jpg">
						<h5><a href="#">Xiaomi 14T</a></h5>
					</div>
				</div>
				<div class="col-lg-3">
					<div class="categories__item set-bg" data-setbg="../LayoutElectronic/img/categories/catdt-5.jpg">
						<h5><a href="#">Galaxy Z Fold 6</a></h5>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- Categories Section End -->

<section class="featured spad">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="section-title">
					<h2>Featured Product</h2>
				</div>
				<div class="featured__controls">
					<ul>
						<li class="active" data-filter="*">All</li>
						<li data-filter=".oranges">Điện thoại</li>
						<li data-filter=".fresh-meat">Đồng hồ</li>
						<li data-filter=".vegetables">Tablet</li>
						<li data-filter=".fastfood">Laptop</li>
					</ul>
				</div>
			</div>
		</div>

		<div class="row featured__filter">
			@foreach (var product in Model)
			{
				<div class="col-lg-3 col-md-4 col-sm-6 mix vegetables fresh-meat">

					<div class="featured__item">
						<div class="featured__item__pic set-bg"
							 data-setbg="">
							<img src="@product.HINH_SANPHAM" />
							<ul class="featured__item__pic__hover">
								<li>
									<a href="#"><i class="fa fa-heart"></i></a>
								</li>
								<li>
									<a asp-controller="Product" asp-action="Details" asp-route-maSP="@product.MA_SANPHAM"><i class="fa fa-retweet"></i></a>
								</li>
								<li>
									<a asp-controller="ShoppingCart" asp-action="AddToCart" ><i class="fa fa-shopping-cart"></i></a>
								</li>
							</ul>
						</div>
						<div class="featured__item__text">
							<h6><a href="#">@product.TEN_SANPHAM</a></h6>
							<h5>@product.GIA_SANPHAM</h5>
						</div>
					</div>
				</div>
			}
		</div>
	</div>
</section>

<script>
	function addToCart(maSanPham) {
		// Gửi yêu cầu AJAX để thêm sản phẩm vào giỏ hàng
		$.ajax({
			url: '@Url.Action("AddToCart", "Cart")', // Đường dẫn tới action trong controller
			type: 'POST',
			data: { maSanPham: maSanPham, soLuong: 1 }, // Số lượng mặc định là 1
			success: function (response) {
				if (response.success) {
					alert('Sản phẩm đã được thêm vào giỏ hàng!'); // Thông báo thành công
				} else {
					alert('Có lỗi xảy ra, vui lòng thử lại.'); // Thông báo lỗi
				}
			},
			error: function () {
				alert('Có lỗi xảy ra, vui lòng thử lại.'); // Thông báo lỗi
			}
		});
	}
</script>